format = """
[‚ñë‚ñí‚ñì](#a3aed2)\
[ üçï ](fg:#090c0c bg:#a3aed2)\
$os\
$shell\
[ÓÇ¥](fg:#5e7fc0 bg:#769ff0)\
$directory\
[ÓÇ¥](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_state\
[ÓÇ¥](fg:#394260 bg:#1d2230)\
$cmd_duration\
$memory_usage\
$battery\
$time\
[ÓÇ¥ ](fg:#1d2230)\
\n$character"""

[os]
disabled = false
style = "fg:#e3e5e5 bg:#5e7fc0"
format = "[ $symbol - ]($style)"

[os.symbols]
Windows = "Windows"

[shell]
disabled = false
style = "fg:#e3e5e5 bg:#5e7fc0"
format = '[$indicator$shlvl ]($style)'
pwsh_indicator = "pwsh"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "

[git_branch]
symbol = "Ôêò"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_state]
style = "bg:#394260"
format = '[[($state($progress_current/$progress_total) )](fg:#769ff0 bg:#394260)]($style)'

[cmd_duration]
min_time = 2000
style = "fg:#a0a9cb bg:#1d2230"
format = "[ Û±é´ $duration ]($style)"
disabled = false

[memory_usage]
threshold = -1
style = "fg:#a0a9cb bg:#1d2230"
format = "[ Û∞çõ $percentage ]($style)"
disabled = false

[battery]
full_symbol = "Û∞Åπ "
charging_symbol = "Û∞ÇÑ "
discharging_symbol = "Û∞ÇÉ "
format = "[$symbol$percentage]($style)"
[[battery.display]]
threshold = 10
style = "fg:#ff5555 bg:#1d2230"
[[battery.display]]
threshold = 100
style = "fg:#a0a9cb bg:#1d2230"

[time]
disabled = false
time_format = "%F %T.%3f"
style = "bg:#1d2230"
format = '[[ Ôê∫ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
