#
# neko3cs rio config
#

cursor = 'â–‡'
blinking-cursor = false
confirm-before-quit = false

[window]
width = 900
height = 600

[fonts]
size = 14

[fonts.regular]
family = "CaskaydiaCove Nerd Font"
style = "normal"
weight = 400

[fonts.bold]
family = "CaskaydiaCove Nerd Font"
style = "normal"
weight = 800

[fonts.italic]
family = "CaskaydiaCove Nerd Font"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "CaskaydiaCove Nerd Font"
style = "italic"
weight = 800
